//
//  DefectRegistry.swift
//  ChaosBank
//
//  The single catalog. Every defect is declared here exactly once, with its
//  category. The seed → active-defects mapping lives here too.
//

import Foundation

nonisolated enum DefectRegistry {
    /// The full catalog. Order matches DefectID.allCases.
    static let all: [Defect] = [
        Defect(id: .roundingDrift, title: "Conversion rounds wrong into history",
               feature: "Exchange / Order", category: .money, severity: .major,
               violates: "Displayed value and stored value are identical, correctly rounded (Decimal).",
               flakiness: .deterministic),
        Defect(id: .pnlSign, title: "Loss displayed as gain",
               feature: "Portfolio", category: .money, severity: .critical,
               violates: "P&L sign matches actual gain/loss.",
               flakiness: .deterministic),
        Defect(id: .exchangeFeeNotApplied, title: "Exchange ignores the fee it displays",
               feature: "Exchange", category: .money, severity: .major,
               violates: "The credited amount reflects the displayed fee.",
               flakiness: .deterministic),
        Defect(id: .pnlPercentVsValue, title: "P&L % divides by market value, not cost",
               feature: "Portfolio", category: .money, severity: .major,
               violates: "P&L percent is measured against cost basis.",
               flakiness: .deterministic),
        Defect(id: .homeTotalOmitsAccount, title: "Total balance omits an account",
               feature: "Home", category: .money, severity: .major,
               violates: "Total balance sums every account.",
               flakiness: .deterministic),

        Defect(id: .limitValidation, title: "Bad limit orders accepted silently",
               feature: "Order", category: .validation, severity: .major,
               violates: "Limit sell below market warns; qty must be > 0.",
               flakiness: .deterministic),
        Defect(id: .zeroAmountAccepted, title: "Zero-amount transfer allowed",
               feature: "Transfer", category: .validation, severity: .major,
               violates: "Continue requires an amount greater than zero.",
               flakiness: .deterministic),
        Defect(id: .whitespaceRecipient, title: "Recipient whitespace not trimmed",
               feature: "Transfer", category: .validation, severity: .minor,
               violates: "Leading/trailing whitespace is trimmed before validation.",
               flakiness: .deterministic),
        Defect(id: .passcodeWeakAccepted, title: "Short passcode accepted",
               feature: "Auth", category: .validation, severity: .major,
               violates: "The app passcode must be the full required length.",
               flakiness: .deterministic),
        Defect(id: .amountExceedsBalanceAllowed, title: "Transfer over balance allowed",
               feature: "Transfer", category: .validation, severity: .major,
               violates: "Continue is blocked when the amount exceeds the balance.",
               flakiness: .deterministic),

        Defect(id: .localeParse, title: "1,000.50 parsed as 1.00050",
               feature: "Exchange / Transfer", category: .localization, severity: .major,
               violates: "Amounts parse correctly under the active locale.",
               flakiness: .deterministic),
        Defect(id: .dateTimezoneShift, title: "Transaction date shifts by timezone",
               feature: "Transactions", category: .localization, severity: .minor,
               violates: "Dates render in a stable, correct timezone.",
               flakiness: .deterministic),
        Defect(id: .rtlBreaksLayout, title: "Row doesn't mirror under RTL",
               feature: "Transactions", category: .localization, severity: .major,
               violates: "Under a right-to-left layout, rows mirror correctly (start/end, not hard-coded left/right).",
               flakiness: .deterministic),
        Defect(id: .numberGroupingIgnoresLocale, title: "Number grouping ignores the locale",
               feature: "Localization", category: .localization, severity: .major,
               violates: "Grouping and decimal separators follow the selected locale (e.g. 1.234,56 in de-DE).",
               flakiness: .deterministic),

        Defect(id: .staleBalance, title: "Dashboard shows pre-transfer balance",
               feature: "Home", category: .state, severity: .major,
               violates: "Balance reflects latest state after any mutation.",
               flakiness: .deterministic),
        Defect(id: .paginationDup, title: "Transaction duplicated after Load more",
               feature: "Transactions", category: .state, severity: .minor,
               violates: "Each transaction appears once.",
               flakiness: .deterministic),
        Defect(id: .paginationNeverEnds, title: "Pagination never ends",
               feature: "Transactions", category: .state, severity: .major,
               violates: "Pagination terminates once every matching row is shown.",
               flakiness: .deterministic),
        Defect(id: .cardToggleInvert, title: "Freeze toggle reads back inverted",
               feature: "Card", category: .state, severity: .major,
               violates: "Toggle state persists and reads back correctly.",
               flakiness: .deterministic),
        Defect(id: .filterLeaksCategory, title: "Money-in filter leaks money-out rows",
               feature: "Transactions", category: .state, severity: .major,
               violates: "A filter shows only its own category.",
               flakiness: .deterministic),
        Defect(id: .orderStuckPending, title: "Filled order still shows pending",
               feature: "Order", category: .state, severity: .major,
               violates: "A filled order reports filled, not pending.",
               flakiness: .deterministic),

        Defect(id: .doubleCharge, title: "Rapid double-tap sends twice",
               feature: "Transfer", category: .concurrency, severity: .critical,
               violates: "Confirm is idempotent; one tap = one transaction.",
               flakiness: .raceCondition),
        Defect(id: .livePriceRace, title: "Order price ≠ tapped price",
               feature: "Markets / Order", category: .concurrency, severity: .critical,
               violates: "Confirmation price equals the price acted on.",
               flakiness: .raceCondition),
        Defect(id: .orderDoubleSubmit, title: "Rapid double-tap places two orders",
               feature: "Order", category: .concurrency, severity: .critical,
               violates: "Place is idempotent; one tap = one order.",
               flakiness: .raceCondition),
        Defect(id: .exchangeDoubleSubmit, title: "Rapid double-tap exchanges twice",
               feature: "Exchange", category: .concurrency, severity: .critical,
               violates: "Execute is idempotent; one tap = one exchange.",
               flakiness: .raceCondition),

        Defect(id: .transactionsHeavyList, title: "History renders a huge non-lazy list",
               feature: "Transactions", category: .performance, severity: .major,
               violates: "Long lists render lazily and stay smooth.",
               flakiness: .deterministic),
        Defect(id: .mainThreadStall, title: "Portfolio blocks the main thread on open",
               feature: "Portfolio", category: .performance, severity: .major,
               violates: "Work stays off the main thread; the UI never hangs.",
               flakiness: .deterministic),
        Defect(id: .feedPollsTooOften, title: "Live feed polls 10× too often",
               feature: "Markets", category: .performance, severity: .minor,
               violates: "The live feed polls at a sane interval.",
               flakiness: .deterministic),
        Defect(id: .transactionsSortEveryRender, title: "History re-sorts on every render",
               feature: "Transactions", category: .performance, severity: .minor,
               violates: "Expensive work is not redone on every render.",
               flakiness: .deterministic),

        Defect(id: .disabledButtonTappable, title: "Button looks disabled but still fires",
               feature: "Transfer", category: .ui, severity: .major,
               violates: "A disabled-looking control is actually non-interactive.",
               flakiness: .deterministic),
        Defect(id: .otpResendNoCooldown, title: "OTP resend ignores the cooldown",
               feature: "Auth", category: .ui, severity: .minor,
               violates: "Resend is blocked until the cooldown elapses.",
               flakiness: .deterministic),
        Defect(id: .successToastMissing, title: "No success toast after a transfer",
               feature: "Transfer", category: .ui, severity: .minor,
               violates: "A successful action shows a confirmation toast.",
               flakiness: .deterministic),

        Defect(id: .duplicateAssetA11yId, title: "Two market rows share one identifier",
               feature: "Markets", category: .accessibility, severity: .major,
               violates: "Every element has a unique, stable accessibility identifier.",
               flakiness: .deterministic),
        Defect(id: .missingA11yLabel, title: "Place-order button has no accessibility label",
               feature: "Order", category: .accessibility, severity: .major,
               violates: "Every control exposes a meaningful accessibility label.",
               flakiness: .deterministic),
        Defect(id: .wrongA11yLabel, title: "Buy button is labelled 'Sell'",
               feature: "Asset detail", category: .accessibility, severity: .critical,
               violates: "A control's accessibility label matches its action.",
               flakiness: .deterministic),

        Defect(id: .authBypass, title: "Gate skipped after backgrounding",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Sensitive screens always require the gate.",
               flakiness: .deterministic),
        Defect(id: .noPrivacyBlur, title: "Sensitive data visible in app switcher",
               feature: "Card / Auth", category: .security, severity: .major,
               violates: "Sensitive screens are obscured when the app is inactive.",
               flakiness: .deterministic),
        Defect(id: .otpAcceptsExpired, title: "Expired OTP still accepted",
               feature: "Auth", category: .security, severity: .critical,
               violates: "An expired one-time code is rejected.",
               flakiness: .deterministic),
        Defect(id: .otpNoLockout, title: "No lockout after repeated wrong OTP",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Too many wrong codes locks the OTP step.",
               flakiness: .deterministic),
        Defect(id: .sessionTimeoutDisabled, title: "Session never times out",
               feature: "Auth", category: .security, severity: .major,
               violates: "An idle session re-locks after the timeout.",
               flakiness: .deterministic),
        Defect(id: .tokenInUserDefaults, title: "Session token stored in UserDefaults",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Secrets live in the Keychain, never in UserDefaults.",
               flakiness: .deterministic),
        Defect(id: .cardNumberFullyVisible, title: "Full card number shown unmasked",
               feature: "Card", category: .security, severity: .critical,
               violates: "The card PAN is masked except the last 4 digits.",
               flakiness: .deterministic),
        Defect(id: .cardCvvVisible, title: "CVV shown on the card face",
               feature: "Card", category: .security, severity: .critical,
               violates: "The CVV is never displayed on screen.",
               flakiness: .deterministic),
        Defect(id: .otpCodeInLog, title: "OTP code written to the console log",
               feature: "Auth", category: .security, severity: .major,
               violates: "Secrets are never logged.",
               flakiness: .deterministic),

        Defect(id: .retryDuplicate, title: "Retry after slow response duplicates the payment",
               feature: "Transfer / Network", category: .network, severity: .critical,
               violates: "Retries are idempotent; a retried request never double-posts.",
               flakiness: .raceCondition),
        Defect(id: .slowResponseRace, title: "Stale response overwrites fresh state",
               feature: "Markets / Network", category: .network, severity: .major,
               violates: "An out-of-order/late response never clobbers newer data.",
               flakiness: .raceCondition),
        Defect(id: .timeoutAsSuccess, title: "Timeout shown as a successful transfer",
               feature: "Transfer / Network", category: .network, severity: .critical,
               violates: "A failed/timed-out request is surfaced as an error, not success.",
               flakiness: .deterministic),
        Defect(id: .staleOfflineBalance, title: "Offline cache shows an outdated balance",
               feature: "Home / Network", category: .network, severity: .major,
               violates: "A stale cache is refreshed or clearly marked as stale.",
               flakiness: .deterministic),

        // MARK: - Batch: money
        Defect(id: .balanceFloorRounded, title: "Total balance floored, not rounded",
               feature: "Home", category: .money, severity: .minor,
               violates: "Balances round to the nearest cent.", flakiness: .deterministic),
        Defect(id: .todayChangeSignFlipped, title: "Today's change sign flipped",
               feature: "Home", category: .money, severity: .major,
               violates: "The daily change sign matches the actual move.", flakiness: .deterministic),
        Defect(id: .transferDebitsWrongAccount, title: "Transfer debits the wrong account",
               feature: "Transfer", category: .money, severity: .critical,
               violates: "A transfer debits the selected account.", flakiness: .deterministic),
        Defect(id: .balanceAfterAdds, title: "'Balance after' adds instead of subtracts",
               feature: "Transfer", category: .money, severity: .major,
               violates: "Balance-after = balance − amount.", flakiness: .deterministic),
        Defect(id: .transferRoundsUp, title: "Transfer amount rounded up",
               feature: "Transfer", category: .money, severity: .major,
               violates: "The exact amount is transferred.", flakiness: .deterministic),
        Defect(id: .exchangeInverseRate, title: "Exchange uses the inverse rate",
               feature: "Exchange", category: .money, severity: .critical,
               violates: "Conversion uses the correct directional rate.", flakiness: .deterministic),
        Defect(id: .exchangeCreditsWrongAccount, title: "Exchange credits the wrong account",
               feature: "Exchange", category: .money, severity: .critical,
               violates: "The bought currency lands in its account.", flakiness: .deterministic),
        Defect(id: .exchangeFeeDoubled, title: "Exchange fee charged twice",
               feature: "Exchange", category: .money, severity: .major,
               violates: "The fee is charged once.", flakiness: .deterministic),
        Defect(id: .youGetShowsGross, title: "'You get' shows the pre-fee amount",
               feature: "Exchange", category: .money, severity: .major,
               violates: "'You get' shows the net, post-fee amount.", flakiness: .deterministic),
        Defect(id: .changePctSignFlipped, title: "Market % change sign flipped",
               feature: "Markets", category: .money, severity: .major,
               violates: "The percent change sign matches the price move.", flakiness: .deterministic),
        Defect(id: .detailPriceOffset, title: "Asset detail price is offset",
               feature: "Asset detail", category: .money, severity: .major,
               violates: "The detail price matches the market price.", flakiness: .deterministic),
        Defect(id: .detailChangeWrongBase, title: "Detail % uses base, not day open",
               feature: "Asset detail", category: .money, severity: .minor,
               violates: "Percent change is measured against the day open.", flakiness: .deterministic),
        Defect(id: .estTotalIgnoresQty, title: "Order total ignores quantity",
               feature: "Order", category: .money, severity: .critical,
               violates: "Estimated total = quantity × price.", flakiness: .deterministic),
        Defect(id: .limitExecutesAtMarket, title: "Limit order executes at market",
               feature: "Order", category: .money, severity: .major,
               violates: "A limit order executes at the limit price.", flakiness: .deterministic),
        Defect(id: .holdingValueUsesCost, title: "Holding value uses cost, not price",
               feature: "Portfolio", category: .money, severity: .major,
               violates: "Position value uses the live price.", flakiness: .deterministic),
        Defect(id: .totalValueOmitsHolding, title: "Portfolio total omits a holding",
               feature: "Portfolio", category: .money, severity: .major,
               violates: "Invested value sums every holding.", flakiness: .deterministic),
        Defect(id: .pnlPercentAbsOnly, title: "P&L % shown as absolute value",
               feature: "Portfolio", category: .money, severity: .major,
               violates: "P&L percent keeps its sign.", flakiness: .deterministic),

        // MARK: - Batch: validation
        Defect(id: .transferNegativeCredits, title: "Negative transfer amount accepted",
               feature: "Transfer", category: .validation, severity: .major,
               violates: "Transfer amounts must be positive.", flakiness: .deterministic),
        Defect(id: .exchangeSameCurrencyAllowed, title: "Exchange to the same currency allowed",
               feature: "Exchange", category: .validation, severity: .minor,
               violates: "Sell and get currencies must differ.", flakiness: .deterministic),
        Defect(id: .searchCaseSensitive, title: "Transaction search is case-sensitive",
               feature: "Transactions", category: .validation, severity: .minor,
               violates: "Search is case-insensitive.", flakiness: .deterministic),
        Defect(id: .sellWithoutHoldingReviewable, title: "Sell reviewable with no holding",
               feature: "Order", category: .validation, severity: .major,
               violates: "You cannot review a sell you can't cover.", flakiness: .deterministic),
        Defect(id: .orderQtyDefaultsZero, title: "Order quantity defaults to zero",
               feature: "Order", category: .validation, severity: .minor,
               violates: "The order ticket opens with a valid quantity.", flakiness: .deterministic),
        Defect(id: .loginAcceptsEmptyCreds, title: "Login accepts empty credentials",
               feature: "Auth", category: .validation, severity: .major,
               violates: "Login requires a username and password.", flakiness: .deterministic),
        Defect(id: .cardLimitAcceptsZero, title: "Card monthly limit accepts zero",
               feature: "Card", category: .validation, severity: .minor,
               violates: "The monthly limit must be positive.", flakiness: .deterministic),

        // MARK: - Batch: localization
        Defect(id: .balanceWrongCurrencySymbol, title: "Balance always shows the € symbol",
               feature: "Home", category: .localization, severity: .major,
               violates: "The currency symbol matches the selected currency.", flakiness: .deterministic),
        Defect(id: .priceMissingDecimals, title: "Prices shown without decimals",
               feature: "Markets", category: .localization, severity: .minor,
               violates: "Prices show two fraction digits.", flakiness: .deterministic),
        Defect(id: .searchTrimsNothing, title: "Search doesn't trim whitespace",
               feature: "Transactions", category: .localization, severity: .minor,
               violates: "Search input is trimmed before matching.", flakiness: .deterministic),

        // MARK: - Batch: state / navigation
        Defect(id: .quickActionTransferOpensExchange, title: "Transfer action opens Exchange",
               feature: "Home", category: .state, severity: .major,
               violates: "Each quick action opens its own screen.", flakiness: .deterministic),
        Defect(id: .recentActivityShowsTwo, title: "Recent activity shows too few rows",
               feature: "Home", category: .state, severity: .minor,
               violates: "Recent activity shows the last four items.", flakiness: .deterministic),
        Defect(id: .exchangeRateStaleAfterSwap, title: "Rate stale after swapping direction",
               feature: "Exchange", category: .state, severity: .major,
               violates: "The rate recomputes when the pair changes.", flakiness: .deterministic),
        Defect(id: .filterOutLeaksIn, title: "Money-out filter leaks money-in rows",
               feature: "Transactions", category: .state, severity: .major,
               violates: "A filter shows only its own category.", flakiness: .deterministic),
        Defect(id: .searchIgnoresCategory, title: "Search ignores the category field",
               feature: "Transactions", category: .state, severity: .minor,
               violates: "Search matches title and category.", flakiness: .deterministic),
        Defect(id: .cryptoShownInStocks, title: "Crypto appears in the Stocks segment",
               feature: "Markets", category: .state, severity: .minor,
               violates: "Each segment shows only its asset kind.", flakiness: .deterministic),
        Defect(id: .watchlistShowsAll, title: "Watchlist shows every asset",
               feature: "Markets", category: .state, severity: .minor,
               violates: "The watchlist shows only watched symbols.", flakiness: .deterministic),
        Defect(id: .assetRowOpensWrongDetail, title: "Tapping an asset opens the wrong one",
               feature: "Markets", category: .state, severity: .critical,
               violates: "Tapping a row opens that row's asset.", flakiness: .deterministic),
        Defect(id: .buyButtonPlacesSell, title: "Buy opens a Sell order ticket",
               feature: "Asset detail", category: .state, severity: .critical,
               violates: "The Buy button starts a buy order.", flakiness: .deterministic),
        Defect(id: .buySellSwapped, title: "Buy side actually sells",
               feature: "Order", category: .state, severity: .critical,
               violates: "The buy side buys.", flakiness: .deterministic),
        Defect(id: .onlinePaymentsInverted, title: "Online-payments toggle reads inverted",
               feature: "Card", category: .state, severity: .major,
               violates: "Toggle state persists and reads back correctly.", flakiness: .deterministic),
        Defect(id: .transferConfirmWrongRecipient, title: "Confirm sheet shows wrong recipient",
               feature: "Transfer", category: .state, severity: .major,
               violates: "The confirmation shows the entered recipient.", flakiness: .deterministic),
        Defect(id: .notificationBadgeStale, title: "Notification badge stays stale",
               feature: "Notifications", category: .state, severity: .minor,
               violates: "The unread badge reflects the actual unread count.", flakiness: .deterministic),
        Defect(id: .notificationOpensWrongScreen, title: "Notification opens the wrong screen",
               feature: "Notifications", category: .state, severity: .major,
               violates: "Tapping a notification opens the destination it names.", flakiness: .deterministic),

        // MARK: - Batch: concurrency
        Defect(id: .homeRefreshRace, title: "Overlapping refreshes clobber the dashboard",
               feature: "Home", category: .concurrency, severity: .major,
               violates: "A stale refresh never overwrites a newer one.", flakiness: .raceCondition),
        Defect(id: .syncLostUpdate, title: "Concurrent increments lose updates",
               feature: "Sync", category: .concurrency, severity: .major,
               violates: "Concurrent read-modify-write increments are atomic; none are lost.", flakiness: .raceCondition),

        // MARK: - Batch: performance
        Defect(id: .sparklineHeavyPoints, title: "Sparklines compute thousands of points",
               feature: "Markets", category: .performance, severity: .minor,
               violates: "Sparklines use a small point budget.", flakiness: .deterministic),
        Defect(id: .transactionsRegroupHeavy, title: "History regroups expensively each render",
               feature: "Transactions", category: .performance, severity: .minor,
               violates: "Grouping is not redone wastefully.", flakiness: .deterministic),

        // MARK: - Batch: UI / layout
        Defect(id: .accountStripHidesGBP, title: "GBP account card hidden",
               feature: "Home", category: .ui, severity: .minor,
               violates: "All accounts appear in the strip.", flakiness: .deterministic),
        Defect(id: .outgoingSignHidden, title: "Outgoing amounts shown without a minus",
               feature: "Transactions", category: .ui, severity: .major,
               violates: "Outgoing amounts show a leading minus.", flakiness: .deterministic),
        Defect(id: .transactionCountWrong, title: "Transaction count label is wrong",
               feature: "Transactions", category: .ui, severity: .minor,
               violates: "The count reflects the filtered total.", flakiness: .deterministic),
        Defect(id: .detailStatHighLowSwapped, title: "Day high/low stats swapped",
               feature: "Asset detail", category: .ui, severity: .minor,
               violates: "High ≥ low in the stats grid.", flakiness: .deterministic),
        Defect(id: .qtyIncrementByTwo, title: "Quantity stepper increments by two",
               feature: "Order", category: .ui, severity: .major,
               violates: "The stepper changes quantity by one.", flakiness: .deterministic),
        Defect(id: .cardExpiryInPast, title: "Card expiry shown in the past",
               feature: "Card", category: .ui, severity: .minor,
               violates: "The displayed expiry is in the future.", flakiness: .deterministic),
        Defect(id: .otpAutoFillsCode, title: "OTP field pre-filled with the real code",
               feature: "Auth", category: .ui, severity: .major,
               violates: "The OTP field starts empty.", flakiness: .deterministic),
        Defect(id: .successToastTooBrief, title: "Success toast flashes too briefly",
               feature: "Transfer", category: .ui, severity: .minor,
               violates: "Confirmation stays visible long enough to read.", flakiness: .deterministic),
        Defect(id: .flakyAnimation, title: "Ticker flash animation is unstable",
               feature: "Markets", category: .ui, severity: .minor,
               violates: "Value-change animations complete within a stable, bounded time.", flakiness: .raceCondition),

        // MARK: - Batch: accessibility
        Defect(id: .marketRowNoLabel, title: "Market rows expose no accessibility label",
               feature: "Markets", category: .accessibility, severity: .major,
               violates: "List rows expose a meaningful label.", flakiness: .deterministic),
        Defect(id: .freezeToggleNoLabel, title: "Freeze toggle has no accessibility label",
               feature: "Card", category: .accessibility, severity: .major,
               violates: "Controls expose a meaningful label.", flakiness: .deterministic),

        // MARK: - Batch: security
        Defect(id: .pinShownPlaintext, title: "PIN shown in plaintext",
               feature: "Card", category: .security, severity: .major,
               violates: "The PIN is masked until explicitly revealed.", flakiness: .deterministic),
        Defect(id: .otpAcceptsAnyCode, title: "OTP accepts any 6-digit code",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Only the correct OTP is accepted.", flakiness: .deterministic),
        Defect(id: .passcodeAnyAccepted, title: "Passcode entry accepts any code",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Only the stored passcode unlocks.", flakiness: .deterministic),
        Defect(id: .passcodeStoredPlaintext, title: "Passcode stored in UserDefaults",
               feature: "Auth", category: .security, severity: .critical,
               violates: "The passcode is never persisted in plaintext.", flakiness: .deterministic),
        Defect(id: .credentialsInLog, title: "Login credentials written to the console",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Credentials are never logged.", flakiness: .deterministic),
        Defect(id: .deepLinkSkipsAuth, title: "Deep link opens a screen without auth",
               feature: "Deep links", category: .security, severity: .critical,
               violates: "A deep link still requires the auth gate before showing content.",
               flakiness: .deterministic),
        Defect(id: .biometricUnlocksFromAnyStage, title: "Biometrics bypass the auth ladder",
               feature: "Auth", category: .security, severity: .critical,
               violates: "Biometrics are a fast re-entry only; they never skip initial login/OTP/passcode.",
               flakiness: .deterministic),

        // MARK: - Batch: network
        Defect(id: .balanceReadReturnsZero, title: "Balance read returns zero on error",
               feature: "Home / Network", category: .network, severity: .major,
               violates: "A read error is surfaced, not shown as a zero balance.", flakiness: .deterministic),
        Defect(id: .transactionsDupOnFetch, title: "Every transaction fetched twice",
               feature: "Transactions / Network", category: .network, severity: .major,
               violates: "A fetch returns each row once.", flakiness: .deterministic),
        Defect(id: .staleHoldingsAfterOrder, title: "Holdings read is stale after an order",
               feature: "Portfolio / Network", category: .network, severity: .major,
               violates: "Reads reflect the latest holdings.", flakiness: .deterministic),
        Defect(id: .offlineBannerMissing, title: "No offline indicator while offline",
               feature: "App / Network", category: .network, severity: .major,
               violates: "When offline, the UI clearly indicates it and serves cached data.", flakiness: .deterministic),
    ]

    static func defect(_ id: DefectID) -> Defect {
        // Force-unwrap is safe: every DefectID has a catalog entry (verified in tests).
        all.first { $0.id == id }!
    }

    static func ids(in category: DefectCategory) -> Set<DefectID> {
        Set(all.filter { $0.category == category }.map(\.id))
    }

    /// Maps a build seed to the set of defects it activates.
    ///
    /// - `0`  → clean baseline (no defects).
    /// - `1…N` → a single defect, in `DefectID.allCases` order (seed 1 = first case).
    /// - `99` → every defect at once.
    ///
    /// Any other seed activates no defects (still a valid, clean build).
    static func defects(forSeed seed: Int) -> Set<DefectID> {
        if seed == 0 { return [] }
        if seed == 99 { return Set(DefectID.allCases) }
        let cases = DefectID.allCases
        if (1...cases.count).contains(seed) {
            return [cases[seed - 1]]
        }
        return []
    }
}
